#  Note:  This form code was originally generated by AdminScriptEditor 4.0 
#         available for free at http://www.itninja.com/community/admin-script-editor 

#  First, let's define our windows form objects...

[void][System.Reflection.Assembly]::LoadWithPartialName("System.Windows.Forms")
[void][System.Reflection.Assembly]::LoadWithPartialName("System.Drawing")

#~~< Form1 >~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
$Form1 = New-Object System.Windows.Forms.Form
$Form1.ClientSize = New-Object System.Drawing.Size(167, 148)
$Form1.Text = "Form1"
#~~< Label1 >~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
$Label1 = New-Object System.Windows.Forms.Label
$Label1.Location = New-Object System.Drawing.Point(41, 50)
$Label1.Size = New-Object System.Drawing.Size(100, 23)
$Label1.TabIndex = 1
$Label1.Text = "Start"
#~~< Button1 >~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
$Button1 = New-Object System.Windows.Forms.Button
$Button1.Location = New-Object System.Drawing.Point(41, 87)
$Button1.Size = New-Object System.Drawing.Size(75, 23)
$Button1.TabIndex = 0
$Button1.Text = "Button1"
$Button1.UseVisualStyleBackColor = $true

# Second, add the controls to the form...
$Form1.Controls.Add($Label1)     #  Add the label to the form.
$Form1.Controls.Add($Button1)    #  Add the button to the form.

# Third the function to handle the button click...
function DaButtonWasClicked( $object ){
  $Label1.Text = "Button Clicked";
}

# Fourth, hook up the button click event to the function that will execute...
$Button1.add_Click({DaButtonWasClicked($Button1)})

# Fifth, declare the function to open the form and start the event trapping...
function Main{
	[System.Windows.Forms.Application]::EnableVisualStyles()
	[System.Windows.Forms.Application]::Run($Form1)
}

#  Finally, call the function Main to open the windows form...
Main # This call must remain below all other event functions
